export type CompanyCategory =
  | "Product"
  | "Startup"
  | "Service"
  | "Fintech"
  | "SaaS"
  | "E-commerce"
  | "Consulting"
  | "Cloud"
  | "Automotive"
  | "Telecom";

export type Company = {
  name: string;
  category: CompanyCategory;
  logo: string;
};

export const companies: Company[] = [
  // PRODUCT / BIG TECH
  { name: "Google", category: "Product", logo: "google" },
  { name: "Microsoft", category: "Product", logo: "microsoft" },
  { name: "Amazon", category: "Product", logo: "amazon" },
  { name: "Apple", category: "Product", logo: "apple" },
  { name: "Meta", category: "Product", logo: "meta" },
  { name: "Netflix", category: "Product", logo: "netflix" },
  { name: "NVIDIA", category: "Product", logo: "nvidia" },
  { name: "Adobe", category: "Product", logo: "adobe" },
  { name: "Intel", category: "Product", logo: "intel" },
  { name: "AMD", category: "Product", logo: "amd" },
  { name: "Qualcomm", category: "Product", logo: "qualcomm" },
  { name: "Cisco", category: "Product", logo: "cisco" },
  { name: "IBM", category: "Product", logo: "ibm" },
  { name: "Oracle", category: "Product", logo: "oracle" },
  { name: "SAP", category: "Product", logo: "sap" },
  { name: "Salesforce", category: "Product", logo: "salesforce" },
  { name: "LinkedIn", category: "Product", logo: "linkedin" },
  { name: "PayPal", category: "Product", logo: "paypal" },
  { name: "Uber", category: "Product", logo: "uber" },
  { name: "Airbnb", category: "Product", logo: "airbnb" },
  { name: "Spotify", category: "Product", logo: "spotify" },
  { name: "Twitter", category: "Product", logo: "x" },
  { name: "Snap", category: "Product", logo: "snapchat" },
  { name: "Pinterest", category: "Product", logo: "pinterest" },
  { name: "Reddit", category: "Product", logo: "reddit" },
  { name: "Dropbox", category: "Product", logo: "dropbox" },
  { name: "GitHub", category: "Product", logo: "github" },
  { name: "GitLab", category: "Product", logo: "gitlab" },
  { name: "Atlassian", category: "Product", logo: "atlassian" },
  { name: "Zoom", category: "Product", logo: "zoom" },
  { name: "Slack", category: "Product", logo: "slack" },
  { name: "Discord", category: "Product", logo: "discord" },
  { name: "Figma", category: "Product", logo: "figma" },
  { name: "Canva", category: "Product", logo: "canva" },
  { name: "Notion", category: "Product", logo: "notion" },
  { name: "Datadog", category: "Product", logo: "datadog" },
  { name: "Palantir", category: "Product", logo: "palantir" },
  { name: "Snowflake", category: "Product", logo: "snowflake" },
  { name: "Databricks", category: "Product", logo: "databricks" },
  { name: "Stripe", category: "Product", logo: "stripe" },
  { name: "Block", category: "Product", logo: "block" },
  { name: "Twilio", category: "Product", logo: "twilio" },
  { name: "Shopify", category: "Product", logo: "shopify" },
  { name: "eBay", category: "Product", logo: "ebay" },
  { name: "Walmart", category: "Product", logo: "walmart" },
  { name: "Target", category: "Product", logo: "target" },
  { name: "Costco", category: "Product", logo: "costco" },

  // INDIA PRODUCT / STARTUPS
  { name: "Flipkart", category: "E-commerce", logo: "flipkart" },
  { name: "PhonePe", category: "Fintech", logo: "phonepe" },
  { name: "Razorpay", category: "Fintech", logo: "razorpay" },
  { name: "Paytm", category: "Fintech", logo: "paytm" },
  { name: "CRED", category: "Fintech", logo: "cred" },
  { name: "Groww", category: "Fintech", logo: "groww" },
  { name: "Zerodha", category: "Fintech", logo: "zerodha" },
  { name: "Policybazaar", category: "Fintech", logo: "policybazaar" },
  { name: "Dream11", category: "Startup", logo: "dream11" },
  { name: "Swiggy", category: "Startup", logo: "swiggy" },
  { name: "Zomato", category: "Startup", logo: "zomato" },
  { name: "Blinkit", category: "Startup", logo: "blinkit" },
  { name: "Zepto", category: "Startup", logo: "zepto" },
  { name: "Meesho", category: "E-commerce", logo: "meesho" },
  { name: "Myntra", category: "E-commerce", logo: "myntra" },
  { name: "Nykaa", category: "E-commerce", logo: "nykaa" },
  { name: "Delhivery", category: "Startup", logo: "delhivery" },
  { name: "Ola", category: "Startup", logo: "ola" },
  { name: "Rapido", category: "Startup", logo: "rapido" },
  { name: "Urban Company", category: "Startup", logo: "urbancompany" },
  { name: "Lenskart", category: "Startup", logo: "lenskart" },
  { name: "OYO", category: "Startup", logo: "oyo" },
  { name: "MakeMyTrip", category: "Startup", logo: "makemytrip" },
  { name: "Freshworks", category: "SaaS", logo: "freshworks" },
  { name: "Zoho", category: "SaaS", logo: "zoho" },
  { name: "Postman", category: "SaaS", logo: "postman" },
  { name: "BrowserStack", category: "SaaS", logo: "browserstack" },
  { name: "Chargebee", category: "SaaS", logo: "chargebee" },
  { name: "Druva", category: "SaaS", logo: "druva" },
  { name: "Mindtickle", category: "SaaS", logo: "mindtickle" },
  { name: "Zoho", category: "SaaS", logo: "zoho" },
  { name: "InMobi", category: "Startup", logo: "inmobi" },
  { name: "Udaan", category: "Startup", logo: "udaan" },
  { name: "Ather Energy", category: "Automotive", logo: "ather" },
  { name: "Cure.fit", category: "Startup", logo: "cultfit" },
  { name: "Unacademy", category: "Startup", logo: "unacademy" },
  { name: "upGrad", category: "Startup", logo: "upgrad" },
  { name: "BYJU'S", category: "Startup", logo: "byjus" },
  { name: "Physics Wallah", category: "Startup", logo: "physicswallah" },
  { name: "PhonePe", category: "Fintech", logo: "phonepe" },

  // BANKING / FINTECH
  { name: "JPMorgan Chase", category: "Fintech", logo: "jpmorgan" },
  { name: "Goldman Sachs", category: "Fintech", logo: "goldmansachs" },
  { name: "Morgan Stanley", category: "Fintech", logo: "morganstanley" },
  { name: "Bank of America", category: "Fintech", logo: "bankofamerica" },
  { name: "Citigroup", category: "Fintech", logo: "citigroup" },
  { name: "Barclays", category: "Fintech", logo: "barclays" },
  { name: "HSBC", category: "Fintech", logo: "hsbc" },
  { name: "Deutsche Bank", category: "Fintech", logo: "deutschebank" },
  { name: "UBS", category: "Fintech", logo: "ubs" },
  { name: "Credit Suisse", category: "Fintech", logo: "creditsuisse" },
  { name: "Visa", category: "Fintech", logo: "visa" },
  { name: "Mastercard", category: "Fintech", logo: "mastercard" },
  { name: "American Express", category: "Fintech", logo: "americanexpress" },
  { name: "Discover", category: "Fintech", logo: "discover" },
  { name: "Coinbase", category: "Fintech", logo: "coinbase" },
  { name: "Robinhood", category: "Fintech", logo: "robinhood" },
  { name: "Revolut", category: "Fintech", logo: "revolut" },
  { name: "Wise", category: "Fintech", logo: "wise" },
  { name: "Klarna", category: "Fintech", logo: "klarna" },
  { name: "Plaid", category: "Fintech", logo: "plaid" },

  // CONSULTING / SERVICES
  { name: "Accenture", category: "Service", logo: "accenture" },
  { name: "TCS", category: "Service", logo: "tcs" },
  { name: "Infosys", category: "Service", logo: "infosys" },
  { name: "Wipro", category: "Service", logo: "wipro" },
  { name: "HCLTech", category: "Service", logo: "hcl" },
  { name: "Tech Mahindra", category: "Service", logo: "techmahindra" },
  { name: "LTIMindtree", category: "Service", logo: "ltimindtree" },
  { name: "Cognizant", category: "Service", logo: "cognizant" },
  { name: "Capgemini", category: "Service", logo: "capgemini" },
  { name: "Deloitte", category: "Consulting", logo: "deloitte" },
  { name: "PwC", category: "Consulting", logo: "pwc" },
  { name: "EY", category: "Consulting", logo: "ey" },
  { name: "KPMG", category: "Consulting", logo: "kpmg" },
  { name: "McKinsey & Company", category: "Consulting", logo: "mckinseycompany" },
  { name: "BCG", category: "Consulting", logo: "bcg" },
  { name: "Bain & Company", category: "Consulting", logo: "bainandcompany" },
  { name: "PwC India", category: "Consulting", logo: "pwc" },
  { name: "Genpact", category: "Service", logo: "genpact" },
  { name: "DXC Technology", category: "Service", logo: "dxc" },
  { name: "NTT DATA", category: "Service", logo: "nttdata" },
  { name: "EPAM", category: "Service", logo: "epam" },
  { name: "Thoughtworks", category: "Service", logo: "thoughtworks" },
  { name: "Publicis Sapient", category: "Service", logo: "publicissapient" },
  { name: "Persistent Systems", category: "Service", logo: "persistent" },
  { name: "Mphasis", category: "Service", logo: "mphasis" },
  { name: "Coforge", category: "Service", logo: "coforge" },
  { name: "Hexaware", category: "Service", logo: "hexaware" },
  { name: "UST", category: "Service", logo: "ust" },
  { name: "Virtusa", category: "Service", logo: "virtusa" },

  // CLOUD / DEVTOOLS
  { name: "Amazon Web Services", category: "Cloud", logo: "amazonaws" },
  { name: "Microsoft Azure", category: "Cloud", logo: "microsoftazure" },
  { name: "Google Cloud", category: "Cloud", logo: "googlecloud" },
  { name: "Oracle Cloud", category: "Cloud", logo: "oracle" },
  { name: "IBM Cloud", category: "Cloud", logo: "ibmcloud" },
  { name: "Cloudflare", category: "Cloud", logo: "cloudflare" },
  { name: "DigitalOcean", category: "Cloud", logo: "digitalocean" },
  { name: "Vercel", category: "Cloud", logo: "vercel" },
  { name: "Netlify", category: "Cloud", logo: "netlify" },
  { name: "Heroku", category: "Cloud", logo: "heroku" },
  { name: "Docker", category: "Cloud", logo: "docker" },
  { name: "Kubernetes", category: "Cloud", logo: "kubernetes" },
  { name: "HashiCorp", category: "Cloud", logo: "hashicorp" },
  { name: "MongoDB", category: "SaaS", logo: "mongodb" },
  { name: "Redis", category: "SaaS", logo: "redis" },
  { name: "Elastic", category: "SaaS", logo: "elastic" },
  { name: "Confluent", category: "SaaS", logo: "confluent" },
  { name: "Grafana Labs", category: "SaaS", logo: "grafana" },
  { name: "CircleCI", category: "SaaS", logo: "circleci" },
  { name: "LaunchDarkly", category: "SaaS", logo: "launchdarkly" },
  { name: "Sentry", category: "SaaS", logo: "sentry" },
  { name: "Amplitude", category: "SaaS", logo: "amplitude" },
  { name: "Segment", category: "SaaS", logo: "segment" },
  { name: "HubSpot", category: "SaaS", logo: "hubspot" },
  { name: "Zendesk", category: "SaaS", logo: "zendesk" },
  { name: "ServiceNow", category: "SaaS", logo: "servicenow" },
  { name: "Workday", category: "SaaS", logo: "workday" },
  { name: "Okta", category: "SaaS", logo: "okta" },
  { name: "Auth0", category: "SaaS", logo: "auth0" },
  { name: "Twilio", category: "SaaS", logo: "twilio" },

  // GLOBAL STARTUPS / SCALEUPS
  { name: "Stripe", category: "Startup", logo: "stripe" },
  { name: "OpenAI", category: "Startup", logo: "openai" },
  { name: "Anthropic", category: "Startup", logo: "anthropic" },
  { name: "Cohere", category: "Startup", logo: "cohere" },
  { name: "Perplexity", category: "Startup", logo: "perplexity" },
  { name: "Hugging Face", category: "Startup", logo: "huggingface" },
  { name: "Scale AI", category: "Startup", logo: "scale" },
  { name: "Databricks", category: "Startup", logo: "databricks" },
  { name: "Mistral AI", category: "Startup", logo: "mistralai" },
  { name: "xAI", category: "Startup", logo: "x" },
  { name: "ByteDance", category: "Startup", logo: "bytedance" },
  { name: "TikTok", category: "Product", logo: "tiktok" },
  { name: "Cloudinary", category: "Startup", logo: "cloudinary" },
  { name: "Brex", category: "Fintech", logo: "brex" },
  { name: "Rippling", category: "SaaS", logo: "rippling" },
  { name: "Gusto", category: "SaaS", logo: "gusto" },
  { name: "Plaid", category: "Fintech", logo: "plaid" },
  { name: "Ramp", category: "Fintech", logo: "ramp" },
  { name: "Toast", category: "Startup", logo: "toast" },
  { name: "DoorDash", category: "Startup", logo: "doordash" },
  { name: "Instacart", category: "Startup", logo: "instacart" },
  { name: "Grubhub", category: "Startup", logo: "grubhub" },
  { name: "Lyft", category: "Startup", logo: "lyft" },
  { name: "Wayfair", category: "E-commerce", logo: "wayfair" },
  { name: "Etsy", category: "E-commerce", logo: "etsy" },
  { name: "Booking.com", category: "Product", logo: "bookingdotcom" },
  { name: "Expedia", category: "Product", logo: "expedia" },
  { name: "Indeed", category: "Product", logo: "indeed" },
  { name: "Glassdoor", category: "Product", logo: "glassdoor" },
  { name: "Coursera", category: "Startup", logo: "coursera" },
  { name: "Udemy", category: "Startup", logo: "udemy" },
  { name: "Duolingo", category: "Startup", logo: "duolingo" },

  // AUTOMOTIVE
  { name: "Tesla", category: "Automotive", logo: "tesla" },
  { name: "BMW", category: "Automotive", logo: "bmw" },
  { name: "Mercedes-Benz", category: "Automotive", logo: "mercedes" },
  { name: "Volkswagen", category: "Automotive", logo: "volkswagen" },
  { name: "Toyota", category: "Automotive", logo: "toyota" },
  { name: "Ford", category: "Automotive", logo: "ford" },
  { name: "General Motors", category: "Automotive", logo: "generalmotors" },
  { name: "Hyundai", category: "Automotive", logo: "hyundai" },
  { name: "Kia", category: "Automotive", logo: "kia" },
  { name: "Volvo", category: "Automotive", logo: "volvo" },
  { name: "Rivian", category: "Automotive", logo: "rivian" },
  { name: "Lucid Motors", category: "Automotive", logo: "lucid" },
  { name: "Tata Motors", category: "Automotive", logo: "tatamotors" },
  { name: "Mahindra", category: "Automotive", logo: "mahindra" },

  // TELECOM
  { name: "Airtel", category: "Telecom", logo: "airtel" },
  { name: "Jio", category: "Telecom", logo: "jio" },
  { name: "Vodafone", category: "Telecom", logo: "vodafone" },
  { name: "Verizon", category: "Telecom", logo: "verizon" },
  { name: "AT&T", category: "Telecom", logo: "att" },
  { name: "T-Mobile", category: "Telecom", logo: "tmobile" },
  { name: "Ericsson", category: "Telecom", logo: "ericsson" },
  { name: "Nokia", category: "Telecom", logo: "nokia" },
  { name: "Samsung", category: "Product", logo: "samsung" },
  { name: "Sony", category: "Product", logo: "sony" },
  { name: "LG", category: "Product", logo: "lg" },

  // MORE MAJOR EMPLOYERS
  { name: "Dell", category: "Product", logo: "dell" },
  { name: "HP", category: "Product", logo: "hp" },
  { name: "Lenovo", category: "Product", logo: "lenovo" },
  { name: "Siemens", category: "Product", logo: "siemens" },
  { name: "Philips", category: "Product", logo: "philips" },
  { name: "Bosch", category: "Product", logo: "bosch" },
  { name: "Honeywell", category: "Product", logo: "honeywell" },
  { name: "PayPal", category: "Fintech", logo: "paypal" },
  { name: "Booking Holdings", category: "Product", logo: "bookingdotcom" },
  { name: "Indeed", category: "Product", logo: "indeed" },
  { name: "McAfee", category: "Product", logo: "mcafee" },
  { name: "Palo Alto Networks", category: "Product", logo: "paloaltonetworks" },
  { name: "CrowdStrike", category: "Product", logo: "crowdstrike" },
  { name: "Fortinet", category: "Product", logo: "fortinet" },
  { name: "VMware", category: "Cloud", logo: "vmware" },
  { name: "Red Hat", category: "Cloud", logo: "redhat" },
  { name: "Canonical", category: "Cloud", logo: "canonical" },
  { name: "Mozilla", category: "Product", logo: "mozilla" },
  { name: "Unity", category: "Product", logo: "unity" },
  { name: "Epic Games", category: "Product", logo: "epicgames" },
  { name: "Electronic Arts", category: "Product", logo: "ea" },
  { name: "Roblox", category: "Product", logo: "roblox" },
  { name: "Samsung", category: "Product", logo: "samsung" },
  { name: "LG Electronics", category: "Product", logo: "lg" },
  { name: "Boeing", category: "Product", logo: "boeing" },
  { name: "Airbus", category: "Product", logo: "airbus" },
  { name: "SpaceX", category: "Startup", logo: "spacex" },
  { name: "NASA", category: "Service", logo: "nasa" }
];
