"use client";

import { useState } from "react";

type CompanyLogoProps = {
  name: string;
  slug: string;
};

const logoSlugs: Record<string, string> = {
  "Google": "google",
  "Microsoft": "microsoft",
  "Amazon": "amazon",
  "Apple": "apple",
  "Meta": "meta",
  "Netflix": "netflix",
  "NVIDIA": "nvidia",
  "Adobe": "adobe",
  "Intel": "intel",
  "AMD": "amd",
  "Qualcomm": "qualcomm",
  "Cisco": "cisco",
  "IBM": "ibm",
  "Oracle": "oracle",
  "SAP": "sap",
  "Salesforce": "salesforce",
  "LinkedIn": "linkedin",
  "PayPal": "paypal",
  "Uber": "uber",
  "Airbnb": "airbnb",
  "Spotify": "spotify",
  "Pinterest": "pinterest",
  "Reddit": "reddit",
  "Dropbox": "dropbox",
  "GitHub": "github",
  "GitLab": "gitlab",
  "Atlassian": "atlassian",
  "Zoom": "zoom",
  "Slack": "slack",
  "Discord": "discord",
  "Figma": "figma",
  "Canva": "canva",
  "Notion": "notion",
  "Datadog": "datadog",
  "Palantir": "palantir",
  "Snowflake": "snowflake",
  "Databricks": "databricks",
  "Stripe": "stripe",
  "Twilio": "twilio",
  "Shopify": "shopify",
  "eBay": "ebay",
  "Walmart": "walmart",
  "Target": "target",

  "Flipkart": "flipkart",
  "PhonePe": "phonepe",
  "Razorpay": "razorpay",
  "Paytm": "paytm",
  "CRED": "cred",
  "Groww": "groww",
  "Zerodha": "zerodha",
  "Policybazaar": "policybazaar",
  "Swiggy": "swiggy",
  "Zomato": "zomato",
  "Blinkit": "blinkit",
  "Zepto": "zepto",
  "Meesho": "meesho",
  "Myntra": "myntra",
  "Nykaa": "nykaa",
  "Delhivery": "delhivery",
  "Ola": "ola",
  "Rapido": "rapido",
  "Urban Company": "urbancompany",
  "Lenskart": "lenskart",
  "OYO": "oyo",
  "MakeMyTrip": "makemytrip",
  "Freshworks": "freshworks",
  "Zoho": "zoho",
  "Postman": "postman",
  "BrowserStack": "browserstack",
  "Chargebee": "chargebee",
  "Druva": "druva",
  "Mindtickle": "mindtickle",
  "InMobi": "inmobi",
  "Udaan": "udaan",
  "Ather Energy": "ather",
  "Unacademy": "unacademy",
  "upGrad": "upgrad",
  "BYJU'S": "byjus",
  "Physics Wallah": "physicswallah",

  "JPMorgan": "jpmorgan",
  "Goldman Sachs": "goldmansachs",
  "Morgan Stanley": "morganstanley",
  "Bank of America": "bankofamerica",
  "Citigroup": "citigroup",
  "Barclays": "barclays",
  "HSBC": "hsbc",
  "Deutsche Bank": "deutschebank",
  "UBS": "ubs",
  "Visa": "visa",
  "Mastercard": "mastercard",
  "American Express": "americanexpress",
  "Coinbase": "coinbase",
  "Robinhood": "robinhood",
  "Revolut": "revolut",
  "Wise": "wise",
  "Klarna": "klarna",
  "Plaid": "plaid",

  "Accenture": "accenture",
  "TCS": "tcs",
  "Infosys": "infosys",
  "Wipro": "wipro",
  "HCLTech": "hcl",
  "Tech Mahindra": "techmahindra",
  "LTIMindtree": "ltimindtree",
  "Cognizant": "cognizant",
  "Capgemini": "capgemini",
  "Deloitte": "deloitte",
  "PwC": "pwc",
  "EY": "ey",
  "KPMG": "kpmg",
  "McKinsey": "mckinsey",
  "BCG": "bcg",
  "Bain": "bain",
  "Genpact": "genpact",
  "DXC": "dxc",
  "NTT DATA": "nttdata",
  "EPAM": "epam",
  "Thoughtworks": "thoughtworks",
  "Publicis Sapient": "publicissapient",
  "Persistent": "persistent",
  "Mphasis": "mphasis",
  "Coforge": "coforge",
  "Hexaware": "hexaware",
  "UST": "ust",

  "AWS": "amazonaws",
  "Azure": "microsoftazure",
  "Google Cloud": "googlecloud",
  "Oracle Cloud": "oracle",
  "IBM Cloud": "ibm",
  "Cloudflare": "cloudflare",
  "DigitalOcean": "digitalocean",
  "Vercel": "vercel",
  "Netlify": "netlify",
  "Heroku": "heroku",
  "Docker": "docker",
  "Kubernetes": "kubernetes",
  "HashiCorp": "hashicorp",
  "MongoDB": "mongodb",
  "Redis": "redis",
  "Elastic": "elastic",
  "Confluent": "confluent",
  "Grafana": "grafana",
  "CircleCI": "circleci",
  "Sentry": "sentry",
  "HubSpot": "hubspot",
  "Zendesk": "zendesk",
  "ServiceNow": "servicenow",
  "Workday": "workday",
  "Okta": "okta",
  "Auth0": "auth0",

  "OpenAI": "openai",
  "Anthropic": "anthropic",
  "Cohere": "cohere",
  "Hugging Face": "huggingface",
  "ByteDance": "bytedance",
  "TikTok": "tiktok",
  "Cloudinary": "cloudinary",
  "Brex": "brex",
  "Rippling": "rippling",
  "Gusto": "gusto",
  "Ramp": "ramp",
  "Toast": "toast",
  "DoorDash": "doordash",
  "Instacart": "instacart",
  "Lyft": "lyft",
  "Wayfair": "wayfair",
  "Etsy": "etsy",
  "Booking.com": "bookingdotcom",
  "Expedia": "expedia",
  "Indeed": "indeed",
  "Glassdoor": "glassdoor",
  "Coursera": "coursera",
  "Udemy": "udemy",
  "Duolingo": "duolingo",

  "Tesla": "tesla",
  "BMW": "bmw",
  "Mercedes-Benz": "mercedes",
  "Volkswagen": "volkswagen",
  "Toyota": "toyota",
  "Ford": "ford",
  "GM": "generalmotors",
  "Hyundai": "hyundai",
  "Kia": "kia",
  "Volvo": "volvo",
  "Rivian": "rivian",
  "Lucid": "lucid",
  "Tata Motors": "tatamotors",
  "Mahindra": "mahindra",

  "Airtel": "airtel",
  "Jio": "jio",
  "Vodafone": "vodafone",
  "Verizon": "verizon",
  "AT&T": "att",
  "T-Mobile": "tmobile",
  "Ericsson": "ericsson",
  "Nokia": "nokia",
  "Samsung": "samsung",
  "Sony": "sony",
  "LG": "lg",

  "Dell": "dell",
  "HP": "hp",
  "Lenovo": "lenovo",
  "Siemens": "siemens",
  "Philips": "philips",
  "Bosch": "bosch",
  "Honeywell": "honeywell",
  "McAfee": "mcafee",
  "Palo Alto Networks": "paloaltonetworks",
  "CrowdStrike": "crowdstrike",
  "Fortinet": "fortinet",
  "VMware": "vmware",
  "Red Hat": "redhat",
  "Canonical": "canonical",
  "Mozilla": "mozilla",
  "Unity": "unity",
  "Epic Games": "epicgames",
  "EA": "ea",
  "Roblox": "roblox",
  "Boeing": "boeing",
  "Airbus": "airbus",
  "SpaceX": "spacex",
  "NASA": "nasa"
};

export default function CompanyLogo({
  name,
  slug,
}: CompanyLogoProps) {
  const [failed, setFailed] = useState(false);

  const actualSlug = logoSlugs[name] || slug;

  if (failed) {
    return (
      <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#edf3fb] text-sm font-black text-[#10254e]">
        {name
          .split(" ")
          .map((word) => word[0])
          .join("")
          .slice(0, 2)}
      </div>
    );
  }

  return (
    <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white">
      <img
        src={`https://cdn.simpleicons.org/${actualSlug}`}
        alt={`${name} logo`}
        className="h-7 w-7 object-contain"
        loading="lazy"
        onError={() => setFailed(true)}
      />
    </div>
  );
}
