"""create users table

Revision ID: 5acc4e4176f6
Revises: 
Create Date: 2026-09-10 15:41:43.016788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5acc4e4176f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
